name: Run azure-search-documents package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: ServiceName
    value: 'Search'
  - name: PackageName
    value: 'azure-search-documents'

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: $(ServiceName)
      PackageName: $(PackageName)

