name: Run azure-appconfiguration package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: ServiceName
    value: 'App Configuration'
  - name: PackageName
    value: 'azure-appconfiguration'

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: $(ServiceName)
      PackageName: $(PackageName)

