
parameters:
- name: AzureDevOpsPat
  type: string
  default: ''
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''
- name: Branch
  type: string
  default: ''

jobs:
  - template: /eng/pipelines/common/content-validation-for-dotnet.yml
    parameters:
      Branch: ${{ parameters.Branch }}
      PackageName: 'microsoft-azure-devices-protocolgateway-providers-cloudstorage'
      ReadmeName: 'iot/microsoft.azure.devices.protocolgateway.providers.cloudstorage'
      jobDisplayName: 'MICROSOFT_AZURE_DEVICES_PROTOCOLGATEWAY_PROVIDERS_CLOUDSTORAGE'
      DotNetSdkVersion: '8.0.x'
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      AzureDevOpsPat: ${{ parameters.AzureDevOpsPat }}
